[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "latest"
  DATABASE_URL = "file:./prisma/dev.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
